language: node_js
node_js:
  - "stable"
cache:
  yanr: true
  directories:
  - node_modules
before_script:
  - "yarn global add gatsby"
  - "yarn install"
script:
  - "yarn test"
after_success:
  - "yarn deploy"
